// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7w_aUqymq8xNPhkqyhmG6jrRMUhpiyy8',
    appId: '1:668891255906:web:1a41b3f1ea1d8b6758ed3b',
    messagingSenderId: '668891255906',
    projectId: 'slipless-sxc',
    authDomain: 'slipless-sxc.firebaseapp.com',
    storageBucket: 'slipless-sxc.firebasestorage.app',
    measurementId: 'G-GH4YBV1X44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTowYe5ijXDN7UU9SaESg3E9UiB3npYk',
    appId: '1:668891255906:android:b82a83ef3811857658ed3b',
    messagingSenderId: '668891255906',
    projectId: 'slipless-sxc',
    storageBucket: 'slipless-sxc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUA27XvdfePDtfx0Efr_2gDUIvcDFT5zI',
    appId: '1:668891255906:ios:2f68c8a8274b9c9d58ed3b',
    messagingSenderId: '668891255906',
    projectId: 'slipless-sxc',
    storageBucket: 'slipless-sxc.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUA27XvdfePDtfx0Efr_2gDUIvcDFT5zI',
    appId: '1:668891255906:ios:2f68c8a8274b9c9d58ed3b',
    messagingSenderId: '668891255906',
    projectId: 'slipless-sxc',
    storageBucket: 'slipless-sxc.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7w_aUqymq8xNPhkqyhmG6jrRMUhpiyy8',
    appId: '1:668891255906:web:5bdaecbfff9ed23958ed3b',
    messagingSenderId: '668891255906',
    projectId: 'slipless-sxc',
    authDomain: 'slipless-sxc.firebaseapp.com',
    storageBucket: 'slipless-sxc.firebasestorage.app',
    measurementId: 'G-SK38LN1MZS',
  );
}
